# Site settings
baseurl = "/"

GoogleAnalytics = "UA-132744098-1"

disqusShortname = "mbeayou"

RelativeURLs=true
CanonifyURLs=true

languageCode = "en"
title = "mohammed beayou"
DefaultContentLanguage = "nl"
publishdir = "public"
theme = "tale"

copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

[author]
    name = "mohammed s. beayou"
    email = "msdbgx@gmail.com"

[posts]
other = "Posts"

[Author]
name = "Medo beayou"

[about]
other = "About"

[writtenBy]
other = "Written by"

[on]
other = "on"

[generator]
other = "Made with <a href='https://gohugo.io'>Hugo</a> using the <a href='https://github.com/EmielH/tale-hugo/'>Tale</a> theme."

[publishdate]
other = "{{ .PublishDate.Format \"January 2, 2018\" }}"


